name: Deploy FastAPI App

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Generate timestamp tag
        id: timestamp
        run: echo "TAG=$(date +%Y%m%d%H%M%S)" >> $GITHUB_OUTPUT

      - name: Build Docker Image
        run: |
          docker build -t muzammil98/fastapi-app:latest -t muzammil98/fastapi-app:${{ steps.timestamp.outputs.TAG }} .

#      - name: Lint code
#        run: |
#          pip install flake8
#          flake8 .
#
      - name: Build Docker Image
        run: |
          docker build -t muzammil98/fastapi-app:latest .
      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: muzammil98
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push to DockerHub
        run: |
          docker push muzammil98/fastapi-app:latest
          docker push muzammil98/fastapi-app:${{ steps.timestamp.outputs.TAG }}
#      - name: Push to DockerHub
#        run: |
#          docker push muzammil98/fastapi-app:latest
